FROM maven
WORKDIR /opt/server
COPY pom.xml .
COPY src .
RUN mvn clean package
RUN /opt/server/target/shipping-0.1.jar /opt/server/shipping.jar
ENV CART_ENDPOINT="cart:8080" \
    DB_HOST="mysql"
CMD ["java", "-jar", "shipping.jar"]